version: 2
updates:
  - package-ecosystem: swift
    directory: /mac_app
    schedule:
      interval: weekly
      day: monday
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
